In [2]:
import numpy as np

In [5]:
# Creating matrices using numpy.array()

In [6]:
list1 = [10, 15, 25, 55, 535]
list2 = [3, 6, 9, 12, 15]
list3 = [11, 13, 17, 19, 23]

In [7]:
matrix1 = np.array([list1, list2, list3])

In [8]:
print(matrix1)

[[ 10  15  25  55 535]
 [  3   6   9  12  15]
 [ 11  13  17  19  23]]


In [9]:
print(type(matrix1))

<class 'numpy.ndarray'>


---

In [10]:
# Creating matrix using numpy.reshape()

In [11]:
dimensions = (3, 5)
alphabets = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o']

In [12]:
matrix_c = np.reshape(alphabets, dimensions, "C")

In [13]:
matrix_f = np.reshape(alphabets, dimensions, "F")

In [14]:
print(matrix_c)

[['a' 'b' 'c' 'd' 'e']
 ['f' 'g' 'h' 'i' 'j']
 ['k' 'l' 'm' 'n' 'o']]


In [15]:
print(matrix_f)

[['a' 'd' 'g' 'j' 'm']
 ['b' 'e' 'h' 'k' 'n']
 ['c' 'f' 'i' 'l' 'o']]


In [16]:
print(type(matrix_c))

<class 'numpy.ndarray'>


In [17]:
print(type(matrix_f))

<class 'numpy.ndarray'>


---

In [3]:
data = np.arange(20)

In [4]:
data

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [5]:
data.reshape((5, 4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [8]:
Matr1 = np.reshape(data, (5,4), "C")
Matr2 = np.reshape(data, (5,4), "F")

In [9]:
Matr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [10]:
Matr2

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [12]:
Matr1[2,2]

10

In [14]:
Matr2[0,2]

10