In [1]:
import numpy as np

In [11]:
data = np.arange(1, 16)

In [12]:
matrix1 = np.reshape(data, (5,3), "C")

In [13]:
print(matrix1)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [14]:
matrix2 = np.reshape(data, (5,3), "F")

In [15]:
print(matrix2)

[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]


---

In [16]:
# Dividing a matrix by another matrix

In [17]:
matrix3 = matrix1/ matrix2

In [18]:
print(matrix3)

[[1.         0.33333333 0.27272727]
 [2.         0.71428571 0.5       ]
 [2.33333333 1.         0.69230769]
 [2.5        1.22222222 0.85714286]
 [2.6        1.4        1.        ]]


In [35]:
print(np.matrix.round(matrix3, decimals=2))

[[1.   0.33 0.27]
 [2.   0.71 0.5 ]
 [2.33 1.   0.69]
 [2.5  1.22 0.86]
 [2.6  1.4  1.  ]]


---

In [23]:
# Multiplyig two matrices.
matrix4 = matrix1 * matrix2

In [24]:
matrix4

array([[  1,  12,  33],
       [  8,  35,  72],
       [ 21,  64, 117],
       [ 40,  99, 168],
       [ 65, 140, 225]])

---

In [25]:
# Adding two matrices.
matrix5 = matrix1 + matrix2

In [26]:
matrix5

array([[ 2,  8, 14],
       [ 6, 12, 18],
       [10, 16, 22],
       [14, 20, 26],
       [18, 24, 30]])

---

In [27]:
# Subtracting a matrix from another matrix.

In [28]:
matrix6 = matrix1- matrix2

In [29]:
matrix6

array([[ 0, -4, -8],
       [ 2, -2, -6],
       [ 4,  0, -4],
       [ 6,  2, -2],
       [ 8,  4,  0]])

---

In [31]:
matrix7 = matrix1 % matrix2

In [32]:
matrix7

array([[ 0,  2,  3],
       [ 0,  5,  6],
       [ 1,  0,  9],
       [ 2,  2, 12],
       [ 3,  4,  0]])