In [1]:
list1 = [10, 43, 232, 0, -43]

In [2]:
import numpy as np

In [3]:
arr1 = np.array(list1)

In [4]:
print(arr1)

[ 10  43 232   0 -43]


In [6]:
print(type(arr1))

<class 'numpy.ndarray'>


In [7]:
arr1

array([ 10,  43, 232,   0, -43])

---

In [8]:
list2 = [43, "a", True, "hello", "world", -32, 0]

In [9]:
arr2 = np.array(list2)

In [10]:
arr2

array(['43', 'a', 'True', 'hello', 'world', '-32', '0'], dtype='<U21')

In [11]:
list2.pop()

0

In [12]:
arr1.mean()

48.4

---

In [13]:
list3 = [10, 43, 33.93, -21]

In [14]:
arr3 = np.array(list3)

In [15]:
arr3

array([ 10.  ,  43.  ,  33.93, -21.  ])

In [16]:
print(arr3)

[ 10.    43.    33.93 -21.  ]


---

In [17]:
list4 = [10, 34, 32.2, True]

In [18]:
arr4 = np.array(list4)

In [20]:
arr4

array([10. , 34. , 32.2,  1. ])

---

In [21]:
# Slicing arrays.

In [22]:
list_a = [10, 20, 30, 40, 50]

In [23]:
arr_a = np.array(list_a)

In [24]:
print(arr_a)

[10 20 30 40 50]


In [25]:
# Representation of a slice of same array
arr_b = arr_a[1:4]

In [26]:
print(arr_b)

[20 30 40]


In [27]:
arr_b[:] = 5

In [28]:
print(arr_b)
print(arr_a)

[5 5 5]
[10  5  5  5 50]


In [29]:
# Copy of an array.

In [30]:
arr_c = arr_a.copy()

In [31]:
arr_c

array([10,  5,  5,  5, 50])

In [32]:
arr_c[1:4] = 99

In [33]:
print(arr_c)
print(arr_a)

[10 99 99 99 50]
[10  5  5  5 50]
